# project - name of new project
# start_range - First IP for DHCP
# end_range - Last IP for DHCP
# cidr - Network CIDR
# dns_server - DNS Server IP
# private_key - private key for ssh access

project: test
start_range: 10.10.1.100
end_range: 10.10.1.200
cidr: 10.10.1.0/24
dns_server: 213.133.98.98
private_key: <private key>
